# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 67b08fa1f204754bbea62cdcc3fa28fee21d85ca # 0.5.5
    hooks:
      - id: uv-lock
